# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo This is build pipeline
    ls -la
    pwd
    cat add.js
    cp add.js $(Build.ArtifactStagingDirectory)/.
  displayName: 'Build stage for function app'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'jsdev'
    publishLocation: 'Container'
