# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo This is build pipeline
    ls -la
    pwd
    cat add.js
    cp add.js $(Build.ArtifactStagingDirectory)/.
  displayName: 'Build stage for function app'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'jsdev'
    publishLocation: 'Container'
- task: AzureFunction@1
  inputs:
    function: 'https://jsappdep.azurewebsites.net/api/helloworld?code=d8omNnQguuxNQ/PpAb7nYlm2fmz4p1uKmyy8WJOJlVMpVTlmaQYvJQ=='
    key: 'wf4fIwo316wz2SWpyGpxNuK7sNQxGAs50FA16D6oeAJ6Poi8GwLt1A=='
    method: 'POST'
    body: '{"firstnum":2,
      "second":3}'
    waitForCompletion: 'false'